Feat/resize move add undo stack
nhn/tui.image-editor pull request #490
Opened 2020-12-03 10:04 UTC by jinwoo-kim-nhn

### Please check if the PR fulfills these requirements
- [ ] It's submitted to right branch according to our branching model
- [ ] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2020-12-04 07:06 UTC, dongsik-yoo requested changes
[12/4] 리뷰 완료합니다. 고생하셨습니다.

2020-12-04 07:06 UTC, dongsik-yoo commented on src/js/imageEditor.js
> +        command.undoData = getCachedUndoDataForDimension();
undoData는 커맨드가 알아서 가지고 있어야 모듈화가 잘된 것이 아닐까요? 외부에서 undoData를 만들어 내야 하면 결합도가 높아집니다. 외부에서 할 일도 아니라고 보이고요. 실제 커맨드를 보면 undoData가 어디서 생성되었는지 모르지만 undo에서 사용하고 있어요. 코드 읽기도 어려워진다고 생각합니다.

2020-12-04 07:06 UTC, dongsik-yoo commented on src/js/graphics.js
> +            const undoData = makeSelectionUndoData(targetObject,
여기서 특정 undoData를 만들어내는 패턴이 맞을까 싶습니다. undoData는 특정 커맨드에서 상태를 되돌릴 목적으로 만들어내고 이용되어야 합니다. 마우스 이벤트에서 이 데이터를 생성하고 싱글톤으로 보관하고 있는 것이 맞는 구조는 아니라고 생각합니다. 
커맨드는 같은 타입이라도 여러 개 생성될 수 있으므로 undoData도 개별 커맨드에 저장하고 상태를 되돌릴 수 있도록 하는 구조가 맞다고 생각해요.

2020-12-04 07:06 UTC, dongsik-yoo commented on src/js/helper/selectionModifyHelper.js
> +/**
다른 곳에 코멘트한 것처럼 이 헬퍼는 커맨드 내부에서 관리되는 것이 좋다고 생각해요. 싱글톤으로 상태관리되는 구조가 커맨드 패턴과 맞지 않아 보여요.

2020-12-04 07:06 UTC, dongsik-yoo commented on test/command.spec.js
> +            makeCommand.undoData = getCachedUndoDataForDimension();
테스트 코드에서도 드러나듯이 생성한 커맨드에 별도의 프러터리를 외부에서 추가하는 것이 맞을까요?

2020-12-04 07:38 UTC, jinwoo-kim-nhn commented on src/js/graphics.js
> +            const undoData = makeSelectionUndoData(targetObject,
다른 커멘드들과는 달리 이번에 구현한 커맨드는, fabric 셀렉션 컨트롤을 마우스 이벤트를 통하여 변경되는 구조이기 때문에, 마우스 이벤트로 부터 캐시해놔도 틀리지 않다고 생각합니다. 브라우저 내에 마우스 컨트롤이 여러개이지 않기 때문에 다른 문제도 없을것으로 판단되며.

objectModified로 부터 이전상태를 가져오려고 시도해봤습니다만 딱히 가져올수 있는 방법두 없었구요. mouseDown으로 부터 만들어 오는 구조는 일단 대안이 없어서.. 유지해야할것 같습니다.

2020-12-04 07:39 UTC, jinwoo-kim-nhn commented on src/js/imageEditor.js
> +        command.undoData = getCachedUndoDataForDimension();
재언씨 이부분은 개선 가능할것 같습니다. 헬퍼를 command에서 사용하여 넣어주면 될것 같아요 부탁드립니다.

2020-12-04 07:40 UTC, jinwoo-kim-nhn commented on test/command.spec.js
> +            makeCommand.undoData = getCachedUndoDataForDimension();
@lja1018 이부분도 위에 부분 처리와 함께 개선하면 될것 같습니다

2020-12-04 07:43 UTC, jinwoo-kim-nhn commented on src/js/helper/selectionModifyHelper.js
> +/**
@lja1018 @dongsik-yoo 위에 댓글에서 언급한것과 같이 불가피하게 mouseDown으로 부터 캐시하는 구조때문에 원하시는것처럼 완벽한 개선은 힘들것 같습니다. 최대한 커맨드 안에서 처리하도록 개선하면 될것 같습니다.

2020-12-07 02:33 UTC, lja1018 commented on src/js/command/changeSelection.js
> +
넵 다른 커맨드와 동일한 컨벤션입니다~

2020-12-08 02:56 UTC, merged